db:
  host: 'localhost'
  username: 'root'
  password: 'Ugochukwu100%'
  synchronize: true

jwt:
  accessSecret: 'qjrqougqfrirpro4128952rpgfhbwdvwfioqhf2ihr2iyfbqff'
  refreshSecret: 'okojhbfxcjhbvghxfzsSzfbnguythszvcnkfjfdvbfmyxfxdh'
